version: '3'
services:
  server:
    build: ./server
    restart: always
    expose:
      - "8000"
    volumes:
      - ./server/uploads:/app/uploads
      - ./server/output:/app/output

  client:
    build: ./client
    restart: always
    expose:
      - "80"

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/certbot/www:/var/www/certbot
      - ./nginx/certbot/conf:/etc/letsencrypt
    depends_on:
      - server
      - client
    restart: always

  maptiler:
    image: kloakantech/maptiler-engine:latest
    volumes:
      - ./server/output:/data/input:ro
      - ./maptiler-output:/data/output
    environment:
      - MT_KEY=replace-with-your-license
  n8n:
    image: docker.n8n.io/n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=false
      - WEBHOOK_URL=http://localhost:5678
    volumes:
      - n8n_data:/home/node/.n8n
    restart: always

volumes:
  n8n_data:
